package com.todolist.app.todolist.exportpdf.services;

import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import org.springframework.stereotype.Service;
import org.springframework.web.bind.annotation.GetMapping;

import java.io.ByteArrayOutputStream;

/**
 * Updated by Idho.
 * Date: 06.04.2023
 * Time: 9:11
 */

@Service
public class ExportPdfServices {


    @GetMapping("generate-pdf2")
    public byte[] generatePdf2() throws DocumentException {
        Document document = new Document();
        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        PdfWriter.getInstance(document, baos);

        document.open();
        document.add(new Paragraph("Hello, this is a sample PDF generated by Spring Boot."));

        document.close();
        return baos.toByteArray();

    }

    @GetMapping("generate-pdf")
    public void generatePdf() throws DocumentException {
        Document document = new Document();
        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        PdfWriter.getInstance(document, baos);

        document.open();
        document.add(new Paragraph("Hello, this is a sample PDF generated by Spring Boot."));



        document.close();


    }
}
